version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: WE4BDB
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 5s
      retries: 5

  # --- AJOUT MONGO DB ---
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongo_data:/data/db

  # --- AJOUT MONGO EXPRESS (Optionnel - Interface Web) ---
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopassword
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  php:
    build: ./docker/php
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./Back-end/src:/var/www/html 
    depends_on:
      db:
        condition: service_healthy
      mongodb: # Attend que mongo soit démarré
        condition: service_started

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      db:
        condition: service_healthy

  angular:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - ./Front-end:/app
    command: sh -c "npm install && npm run start -- --host 0.0.0.0"
    depends_on:
      - php

# Ne pas oublier de déclarer le volume pour ne pas perdre tes données Mongo au redémarrage
volumes:
  mongo_data: